### ISSUE TITLE
AttributeError: 'Proxy' object has no attribute 'setdefault'

### ISSUE THREAD

**Issue by zachbellay** [Nekmo/proxy-db#9]
* proxy-db version: 0.2.3
* Python version: 3.6.4
* Operating System: Windows 10

### Description
Attempting to run first script available in the readme.

### What I Did
Copy pasted the first script from the readme and ran it after install proxy-db. The traceback below is the result of running the script.
```
C:\Users\zachb\Desktop\socks-proxy-tester>python proxydb.py
Traceback (most recent call last):
  File "proxydb.py", line 7, in <module>
    requests.get('http://site.com/', proxies=proxy)
  File "C:\Users\zachb\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\zachb\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\zachb\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 524, in request
    prep.url, proxies, stream, verify, cert
  File "C:\Users\zachb\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 702, in merge_environment_settings
    proxies.setdefault(k, v)
AttributeError: 'Proxy' object has no attribute 'setdefault'
```

**Comment by Nekmo** [comment]
```
Python 3.6.6 (default, Aug 24 2018, 13:20:52) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> from requests.exceptions import Timeout, ConnectionError, ProxyError
>>> from proxy_db.proxies import ProxiesList
>>> 
>>> proxy = next(ProxiesList())
>>> try:
...     requests.get('http://site.com/', proxies=proxy)
... except (Timeout, ConnectionError, ProxyError):
...     proxy.negative()
... else:
...     proxy.positive()
... 

<Response [200]>
```
I can not reproduce the error. Can you offer additional information?

**Comment by Nekmo** [comment]
Closed due to inactivity.
